= Introduction
== Four elements of Embedded Linux
*Toolchain*: The compiler and other tools needed to create code for your target device. Everything else depends on the toolchain.

*Bootloader*: The program that initializes the board and loads the Linux kernel.

*Kernel*: This is the heart of the system, managing system resources and interfacing with hardware.

*Root filesystem*: Contains the libraries and programs that are run once the kernel has completed its initialization.

== Yocto project
Yocto project provides *open source, high quality infrastructure and tools* to help developers create *their own custom Linux distributions* for any *hardware architecture*.

* Input: 
** Kernel Configuration 
** Hardware Name 
** Packages/Binaries to be installed

* Output:
** Linux Kernel 
** Root File System
** Bootloader 
** Device Tree
** Toolchain

== Poky
* Poky is a reference distribution of Yocto Project. The word "reference" is used to mean "example" in this context.
* Yocto Project uses Poky to build images (kernel, system, and application software) for targeted hardware.

* Yocto Project uses Poky to build images (kernel, system, and application software) for targeted hardware.

* At the technical level it is a combined repository of the components
** Bitbake
** OpenEmbedded Core
** meta-yocto-bsp
** Documentation

== Metadata
* Metadata refers to the build instructions
* Commands and data used to indicate what versions of software are used
* Where they are obtained from
* Changes or additions to the software itself ( patches ) which are used to fix bugs or customize the software for use in a particular situation

* Metadata is collection of
** Configuration files (.conf)
** Recipes (.bb and .bbappend)
** Classes (.bbclass)
** Includes (.inc)

== OpenEmbedded Project
* OpenEmbedded offers a best-in-class cross-compile environment. It allows developers to create a complete Linux Distribution for embedded systems.

* The Yocto Project and OpenEmbedded share a core collection of metadata called openembedded-core. 

* OpenEmbedded provides a comprehensive set of metadata for a wide variety of architectures, features, and applications

* The Yocto Project focuses on providing powerful, easy-to-use, interoperable, well-tested tools, metadata, and board support packages (BSPs) for a core set of architectures and specific boards.

== Bitbake
* It basically performs the same functionality as of *make*.

* It's a task scheduler that parses *python and shell script* mixed code

* The code parsed generates and runs tasks, which are basically a set of steps ordered according to code's dependencies.

* It reads recipes and follows them by fetching packages, building them and incorporating the results into bootable images.

* It keeps track of all tasks being processed in order to ensure completion, maximizing the use of processing resources to reduce build time and being predictable.

== meta-yocto-bsp
* A Board Support Package (BSP) is a collection of information that defines how to support a particular hardware device, set of devices, or hardware platform

* The BSP includes information about the hardware features present on the device and kernel configuration information along with any additional hardware drivers required.

* The BSP also lists any additional software components required in addition to a generic Linux software stack for both essential and optional platform features.

* The meta-yocto-bsp layer in Poky maintains several BSPs such as the Beaglebone, EdgeRouter, and generic versions of both 32-bit and 64-bit IA machines.

= Yocto Terminology

== Metadata
Poky = Bitbake + Metadata

* Metadata is collection of
** Configuration files (.conf)
** Recipes (.bb and .bbappend)
** Classes (.bbclass)
** Includes (.inc)

== Recipes
* Yocto: A recipe is a set of instructions that is read and processed by the bitbake

* Extension of Recipe: .bb

* A recipe describes:
** where you get source code
** which patches to apply
** Configuration options
** Compile options (library dependencies)
** Install
** License

== Configuration Files

* Files which hold
** global definition of variables
** user defined variables and
** hardware configuration information

* They tell the build system what to build and put into the image to support a particular platform

* Extension: .conf

* Types
** Machine Configuration Options
** Distribution Configuration Options
** Compiler tuning options
** General Common Configuration Options
** User Configuration Options (local.conf)

== Classes

* Class files are used to abstract common functionality and share it amongst multiple recipe (.bb) files

* To use a class file, you simply make sure the recipe inherits the class

* Extension: .bbclass

* They are usually placed in classes directory inside the meta* directory

== Layers

* A collection of *related recipes* or *Layers are recipe containers* (folders)

* Typical naming convention: meta-<layername>

* Poky has the following layers:

meta, meta-poky, meta-selftest, meta-skeleton, meta-yocto-bsp

* Layers provide a mechanism to *isolate meta data* according to *functionality*, for instance BSPs, distribution configuration, etc.

* You could have a BSP layer, a GUI layer, a distro configuration, middleware, or an application

* Putting your entire build into one layer limits and complicates future customization and reuse. 

Example: meta-poky          -- Distro metadata
         meta-yocto-bsp     -- BSP    metadata

* Layers allow to easily to *add entire sets of meta data* and/or *replace sets with other sets*.
meta-poky, is itself a layer applied on top of the OE-Core metadata layer, meta

* BBLAYERS variable present in ``build/conf/bblayers.conf`` file list the layers Bitbake tries to find

* If bblayers.conf is not present when you start the build, the OpenEmbedded build system creates it from *bblayers.conf.sample* when you source the *oe-init-build-env* script

* Command to find out which layers are present _$ bitbake-layers show-layers_

Note: You can include any number of available layers from the Yocto Project 

* Where to get other layers

https://layers.openembedded.org/layerindex/branch/master/layers/

== Image

* An image is the *top level recipe*, it has a description, a license and inherits the *core-image* class

* It is used alongside the machine definition machine describes the hardware used and its capabilities

image is architecture agnostic and defines how the root filesystem is built, with what packages.

* By default, several images are provided in Poky

Command to check the list of available image recipes

_$ ls meta*/recipes*/images/*.bb_

== Packages

* Non-Yocto: Any wrapped or boxed object or group of objects.

* Yocto: A package is a binary file with name *.rpm, *.deb, or *.ipkg

* A single recipe produces many packages. All packages that a recipe generated are listed in the recipe variable

== Poky source tree

* bitbake		-	Holds all Python scripts used by the bitbake command
			bitbake/bin is placed into the PATH environmental variable so bitbake can be found

* documentation   -       All documentation sources for the Yocto Project documentation
			Can be used to generate nice PDFs

* meta		-	Contains the oe-core metadata
			
* meta-poky	-	Holds the *configuration* for the *Poky reference distribution*
			local.conf.sample, bblayers.conf.sample are present here

* meta-skeleton	- 	Contains template recipes for BSP and kernel development


* meta-yocto-bsp  -	Maintains several BSPs such as the Beaglebone, EdgeRouter, 
			and generic versions of both 32-bit and 64-bit IA machines.

* scripts		-	Contains scripts used to set up the environment, development tools,
			and tools to flash the generated images on the target.

* LICENSE		-	The license under which Poky is distributed (a mix of GPLv2 and MIT).