= Introduction
== Four elements of Embedded Linux
*Toolchain*: The compiler and other tools needed to create code for your target device. Everything else depends on the toolchain.

*Bootloader*: The program that initializes the board and loads the Linux kernel.

*Kernel*: This is the heart of the system, managing system resources and interfacing with hardware.

*Root filesystem*: Contains the libraries and programs that are run once the kernel has completed its initialization.

== Yocto project
Yocto project provides *open source, high quality infrastructure and tools* to help developers create *their own custom Linux distributions* for any *hardware architecture*.

* Input: 
**Kernel Configuration 
**Hardware Name 
**Packages/Binaries to be installed

* Output:
**Linux Kernel 
**Root File System
**Bootloader 
**Device Tree
**Toolchain

== Poky
* Poky is a reference distribution of Yocto Project. The word "reference" is used to mean "example" in this context.
* Yocto Project uses Poky to build images (kernel, system, and application software) for targeted hardware.

* Yocto Project uses Poky to build images (kernel, system, and application software) for targeted hardware.

* At the technical level it is a combined repository of the components
**Bitbake
**OpenEmbedded Core
**meta-yocto-bsp
**Documentation

== Metadata
* Metadata refers to the build instructions
* Commands and data used to indicate what versions of software are used
* Where they are obtained from
* Changes or additions to the software itself ( patches ) which are used to fix bugs or customize the software for use in a particular situation

* Metadata is collection of
** Configuration files (.conf)
** Recipes (.bb and .bbappend)
** Classes (.bbclass)
** Includes (.inc)

== OpenEmbedded Project
* OpenEmbedded offers a best-in-class cross-compile environment. It allows developers to create a complete Linux Distribution for embedded systems.

* The Yocto Project and OpenEmbedded share a core collection of metadata called openembedded-core. 

* OpenEmbedded provides a comprehensive set of metadata for a wide variety of architectures, features, and applications

* The Yocto Project focuses on providing powerful, easy-to-use, interoperable, well-tested tools, metadata, and board support packages (BSPs) for a core set of architectures and specific boards.

== Bitbake
* It basically performs the same functionality as of *make*.

* It's a task scheduler that parses *python and shell script* mixed code

* The code parsed generates and runs tasks, which are basically a set of steps ordered according to code's dependencies.

* It reads recipes and follows them by fetching packages, building them and incorporating the results into bootable images.

* It keeps track of all tasks being processed in order to ensure completion, maximizing the use of processing resources to reduce build time and being predictable.

== meta-yocto-bsp
* A Board Support Package (BSP) is a collection of information that defines how to support a particular hardware device, set of devices, or hardware platform

* The BSP includes information about the hardware features present on the device and kernel configuration information along with any additional hardware drivers required.

* The BSP also lists any additional software components required in addition to a generic Linux software stack for both essential and optional platform features.

* The meta-yocto-bsp layer in Poky maintains several BSPs such as the Beaglebone, EdgeRouter, and generic versions of both 32-bit and 64-bit IA machines.

= Yocto Terminology

== Metadata
Poky = Bitbake + Metadata

* Metadata is collection of
** Configuration files (.conf)
** Recipes (.bb and .bbappend)
** Classes (.bbclass)
** Includes (.inc)

== Recipes
*Yocto: A recipe is a set of instructions that is read and processed by the bitbake

*Extension of Recipe: .bb

* A recipe describes:
** where you get source code
** which patches to apply
** Configuration options
** Compile options (library dependencies)
** Install
** License

== Configuration Files

* Files which hold
** global definition of variables
** user defined variables and
** hardware configuration information

* They tell the build system what to build and put into the image to support a particular platform

* Extension: .conf

* Types
** Machine Configuration Options
** Distribution Configuration Options
** Compiler tuning options
** General Common Configuration Options
** User Configuration Options (local.conf)

== Classes

* Class files are used to abstract common functionality and share it amongst multiple recipe (.bb) files

* To use a class file, you simply make sure the recipe inherits the class

* Extension: .bbclass

* They are usually placed in classes directory inside the meta* directory